version: "3.8"

services:
  app:
    image: j0cos/collaborative-text-editor:latest
    network_mode: host

    environment:
      - NODE_ENV=production

  loki:
    image: grafana/loki:2.9.0
    network_mode: host
    ports:
      - "3100:3100"

  promtail:
    image: grafana/promtail:2.9.0
    network_mode: host
    volumes:
      - /var/log/containers:/var/log/containers
      - ./promtail-config.yml:/etc/promtail/config.yml
      - /var/run/docker.sock:/var/run/docker.sock
    user: "root"
    group_add:
      - "113"
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki

  node-exporter:
    image: prom/node-exporter:v1.8.0
    network_mode: host
    ports:
      - "9100:9100"

  prometheus:
    image: prom/prometheus:v2.47.0
    network_mode: host
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:10.0.0
    network_mode: host
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped

#volumes:
volumes:
  grafana-data:
