name: Server Config Deployment

on:
  push:
    branches:
      - server
    paths:
      - 'compose.yaml'
      - 'prometheus.yaml'
      - 'promtail-config.yaml'

jobs:
  deploy-config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy configuration files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "compose.yaml,prometheus.yaml,promtail-config.yaml"
          target: "/root/project/"
